export const medicationsCategories = [
  { "name": "Dipirona", "categories": ["analgesico", "antipiretico"] },
  { "name": "Ibuprofeno", "categories": ["analgesico", "antipiretico", "anti_inflamatorio"] },
  { "name": "Paracetamol", "categories": ["analgesico", "antipiretico"] },
  { "name": "Simeticona", "categories": ["antiflatulento"] },
  { "name": "Dimenidrinato + Piridoxina (Dramin)", "categories": ["antiemetico"] },
  { "name": "Bromoprida", "categories": ["procinetico", "antiemetico"] },
  { "name": "Tramadol", "categories": ["analgesico", "analgesico_opioide"] },
  { "name": "Escopolamina (Buscopan)", "categories": ["antiespasmodico"] },
  { "name": "Cerumin", "categories": ["ceruminolitico"] },
  { "name": "Otosporin", "categories": ["antibiotico_topico", "corticoide_otologico"] },
  { "name": "Diclofenaco", "categories": ["analgesico", "anti_inflamatorio"] },
  { "name": "Azitromicina", "categories": ["antibiotico"] },
  { "name": "Ciprofloxacino", "categories": ["antibiotico"] },
  { "name": "Cefalexina", "categories": ["antibiotico"] },
  { "name": "Prednisona", "categories": ["corticoide", "anti_inflamatorio"] },
  { "name": "Loratadina", "categories": ["anti_histaminico"] },
  { "name": "Ebastina", "categories": ["anti_histaminico"] },
  { "name": "Metoclopramida", "categories": ["procinetico", "antiemetico"] },
  { "name": "Ondansetrona", "categories": ["antiemetico"] },
  { "name": "Ciclobenzaprina (Miosan)", "categories": ["relaxante_muscular"] },
  { "name": "Ivermectina", "categories": ["antiparasitario"] },
  { "name": "Sulfametoxazol Trimetoprima", "categories": ["antibiotico"] },
  { "name": "Naproxeno", "categories": ["analgesico", "antipiretico", "anti_inflamatorio"] },
  { "name": "Sumatriptano", "categories": ["antienxaquecoso", "vasoconstritor"] },
  { "name": "Racecadotrila (Tiorfan)", "categories": ["antidiarreico"] },
  { "name": "Omeprazol", "categories": ["antiulceroso"] },
  { "name": "Paracetamol + Codeína (Tylex)", "categories": ["analgesico", "analgesico_opioide"] },
  { "name": "Nitrofurantoina", "categories": ["antibiotico", "antisseptico_urinario"] },
  { "name": "Tansulosina", "categories": ["bloqueador_alfa_adrenergico"] },
  { "name": "Etoricoxibe (Ecoxe)", "categories": ["analgesico", "anti_inflamatorio"] },
  { "name": "Flunarizina", "categories": ["antienxaquecoso"] },
  { "name": "Valeriana Officinalis", "categories": ["fitoterapico", "ansiolitico"] },
  { "name": "Amoxicilina", "categories": ["antibiotico"] },
  { "name": "Amoxicilina + Clavulanato", "categories": ["antibiotico"] },
  { "name": "Prednisolona", "categories": ["corticoide", "anti_inflamatorio"] },
  { "name": "Dexclorfeniramina", "categories": ["anti_histaminico"] },
  { "name": "Hidroxizina", "categories": ["anti_histaminico", "antipruriginoso"] },
  { "name": "Desloratadina", "categories": ["anti_histaminico"] },
  { "name": "Fexofenadina (Allegra)", "categories": ["anti_histaminico"] },
  { "name": "Lactulose", "categories": ["laxante"] },
  { "name": "Oleo Mineral", "categories": ["laxante"] },
  { "name": "Acebrofilina", "categories": ["broncodilatador", "expectorante"] },
  { "name": "Ambroxol", "categories": ["expectorante", "mucolitico"] },
  { "name": "Acetilcisteina", "categories": ["expectorante", "mucolitico"] },
  { "name": "Levodropropizina", "categories": ["antitussigeno"] },
  { "name": "Claritromicina", "categories": ["antibiotico"] },
  { "name": "Albendazol", "categories": ["antiparasitario", "antihelmintico"] },
  { "name": "Enterogermina", "categories": ["probiotico"] },
  { "name": "Florax", "categories": ["probiotico"] },
  { "name": "Sulfato De Zinco", "categories": ["suplemento_mineral"] },
  { "name": "Hedera Helix", "categories": ["fitoterapico", "expectorante"] },
  { "name": "Vick 44E", "categories": ["expectorante", "antitussigeno"] },
  { "name": "Hidroxido De Aluminio", "categories": ["antiacido"] },
  { "name": "Nistatina", "categories": ["antifungico"] },
  { "name": "Mupirocina", "categories": ["antibiotico_topico"] },
  { "name": "Neomicina Bacitracina", "categories": ["antibiotico_topico"] },
  { "name": "Nebacetin", "categories": ["antibiotico_topico"] },
  { "name": "Cetoconazol", "categories": ["antifungico_topico"] },
  { "name": "Sulfeto De Selenio", "categories": ["antifungico_topico"] },
  { "name": "Permetrina", "categories": ["escabicida", "pediculicida"] },
  { "name": "Enxofre Precipitado", "categories": ["escabicida", "antisseptico_topico"] },
  { "name": "Dexametasona", "categories": ["corticoide", "anti_inflamatorio"] },
  { "name": "Hidrocortisona", "categories": ["corticoide", "anti_inflamatorio"] },
  { "name": "Trok N", "categories": ["antibiotico_topico", "antifungico_topico", "corticoide_topico"] },
  { "name": "Nistatina + Oxido Zinco", "categories": ["antifungico_topico"] },
  { "name": "Creme De Ureia", "categories": ["hidratante"] },
  { "name": "Age Acidos Graxos", "categories": ["hidratante"] },
  { "name": "Flogoral Spray", "categories": ["anestesico_local", "anti_inflamatorio_topico"] },
  { "name": "Permanganato De Potassio", "categories": ["antisseptico_topico"] },
  { "name": "Soro Fisiologico", "categories": ["solucao_salina"] },
  { "name": "Budesonida", "categories": ["corticoide_nasal", "corticoide_inalatorio"] },
  { "name": "Beclometasona", "categories": ["corticoide_nasal", "corticoide_inalatorio"] },
  { "name": "Salbutamol", "categories": ["broncodilatador"] },
  { "name": "Budesonida + Formoterol (Symbicort)", "categories": ["broncodilatador", "corticoide_inalatorio"] },
  { "name": "Tobramicina", "categories": ["antibiotico_oftalmico"] },
  { "name": "Tobramicina + Dexametasona", "categories": ["antibiotico_oftalmico", "corticoide_oftalmico"] },
  { "name": "Carmelose Sodica", "categories": ["lubrificante_ocular"] },
  { "name": "Hialuronato De Sodio", "categories": ["lubrificante_ocular"] },
  { "name": "Ecofilm", "categories": ["lubrificante_ocular"] },
  { "name": "Lacribell", "categories": ["lubrificante_ocular"] },
  { "name": "Moxifloxacino", "categories": ["antibiotico_oftalmico"] },
  { "name": "Macrogol", "categories": ["laxante_osmotico"] },
  { "name": "Metilprednisolona", "categories": ["corticoide", "anti_inflamatorio"] },
  { "name": "Adrenalina", "categories": ["vasopressor", "broncodilatador"] },
  { "name": "Ceftriaxona", "categories": ["antibiotico"] },
  { "name": "Penicilina Benzatina", "categories": ["antibiotico"] },
  { "name": "Benalete", "categories": ["antitussigeno"] }
]
